export const world24Data = {
    id: '024',
    name: 'World 24 - Great Tomb',
    powers: [
      {
        id: 'adventurer-rank',
        name: 'Adventurer Rank',
        type: 'gacha',
        statType: 'energy',
        unlockCost: '10k',
        stats: [
          { id: 'copper-rank', name: 'Copper', multiplier: '1x', rarity: 'Common', probability: 40 },
          { id: 'iron-rank', name: 'Iron', multiplier: '2x', rarity: 'Uncommon', probability: 30 },
          { id: 'silver-rank', name: 'Silver', multiplier: '3x', rarity: 'Rare', probability: 20 },
          { id: 'gold-rank', name: 'Gold', multiplier: '4x', rarity: 'Epic', probability: 5 },
          { id: 'platinum-rank', name: 'Platinum', multiplier: '5x', rarity: 'Legendary', probability: 3 },
          { id: 'mithril-rank', name: 'Mithril', multiplier: '6x', rarity: 'Mythic', probability: 1.5 },
          { id: 'orichalcum-rank', name: 'Orichalcum', multiplier: '8x', rarity: 'Phantom', probability: 0.45 },
          { id: 'adamantite-rank', name: 'Adamantite', multiplier: '10x', rarity: 'Supreme', probability: 0.05 },
        ],
      },
      {
        id: 'magic-tier',
        name: 'Magic Tier',
        type: 'gacha',
        statType: 'damage',
        unlockCost: '10k',
        stats: [
          { id: '1st-tier', name: '1st Tier', multiplier: '1.1x', rarity: 'Common', probability: 40 },
          { id: '2nd-tier', name: '2nd Tier', multiplier: '1.2x', rarity: 'Uncommon', probability: 30 },
          { id: '3rd-tier', name: '3rd Tier', multiplier: '1.3x', rarity: 'Rare', probability: 20 },
          { id: '4th-tier', name: '4th Tier', multiplier: '1.4x', rarity: 'Epic', probability: 5 },
          { id: '5th-tier', name: '5th Tier', multiplier: '1.5x', rarity: 'Legendary', probability: 3 },
          { id: '6th-tier', name: '6th Tier', multiplier: '1.6x', rarity: 'Mythic', probability: 1.5 },
          { id: '7th-tier', name: '7th Tier', multiplier: '1.8x', rarity: 'Phantom', probability: 0.45 },
          { id: '8th-tier', name: '8th Tier', multiplier: '2x', rarity: 'Supreme', probability: 0.05 },
        ],
      },
      {
        id: 'mana-growth',
        name: 'Mana Growth',
        type: 'progression',
        statType: 'energy',
        unlockCost: '5k',
        maxLevel: 100,
        maxBoost: '1.0x Energy',
      },
      {
        id: 'ultimate-cast',
        name: 'Ultimate Cast',
        type: 'progression',
        statType: 'damage',
        unlockCost: '5k',
        maxLevel: 100,
        maxBoost: '1.0x Damage',
      },
    ],
    npcs: [],
    pets: [],
    dungeons: [],
    shadows: [],
    stands: []
  };
