import type { WikiArticle } from '@/lib/types';

export const energyGainPerRankArticle: Omit<WikiArticle, 'createdAt'> = {
    id: 'energy-gain-per-rank',
    title: 'Ganho de Energia Base por Rank',
    summary: 'Uma referência para o ganho de energia base por clique para cada rank no jogo.',
    content: `Esta tabela detalha o ganho de energia base que um jogador recebe por cada clique em um determinado rank. Esse valor pode ser aumentado por vários multiplicadores no jogo.`,
    tags: ['ganho', 'energia', 'rank', 'clique', 'guia', 'geral'],
    imageUrl: 'wiki-2',
    tables: {
      energyGain: {
        headers: ['Rank', 'Ganho de Energia'],
        rows: [
          { 'Rank': 1, 'Ganho de Energia': '4.17e-15' },
          { 'Rank': 2, 'Ganho de Energia': '8.34e-15' },
          { 'Rank': 3, 'Ganho de Energia': '1.67e-14' },
          { 'Rank': 4, 'Ganho de Energia': '3.34e-14' },
          { 'Rank': 5, 'Ganho de Energia': '6.67e-14' },
          { 'Rank': 6, 'Ganho de Energia': '1.33e-13' },
          { 'Rank': 7, 'Ganho de Energia': '2.67e-13' },
          { 'Rank': 8, 'Ganho de Energia': '5.34e-13' },
          { 'Rank': 9, 'Ganho de Energia': '1.07e-12' },
          { 'Rank': 10, 'Ganho de Energia': '2.14e-12' },
          { 'Rank': 11, 'Ganho de Energia': '4.27e-12' },
          { 'Rank': 12, 'Ganho de Energia': '8.55e-12' },
          { 'Rank': 13, 'Ganho de Energia': '1.71e-11' },
          { 'Rank': 14, 'Ganho de Energia': '3.42e-11' },
          { 'Rank': 15, 'Ganho de Energia': '6.84e-11' },
          { 'Rank': 16, 'Ganho de Energia': '1.37e-10' },
          { 'Rank': 17, 'Ganho de Energia': '2.74e-10' },
          { 'Rank': 18, 'Ganho de Energia': '5.47e-10' },
          { 'Rank': 19, 'Ganho de Energia': '1.09e-09' },
          { 'Rank': 20, 'Ganho de Energia': '2.19e-09' },
          { 'Rank': 21, 'Ganho de Energia': '4.38e-09' },
          { 'Rank': 22, 'Ganho de Energia': '8.76e-09' },
          { 'Rank': 23, 'Ganho de Energia': '1.75e-08' },
          { 'Rank': 24, 'Ganho de Energia': '3.50e-08' },
          { 'Rank': 25, 'Ganho de Energia': '7.01e-08' },
          { 'Rank': 26, 'Ganho de Energia': '1.40e-07' },
          { 'Rank': 27, 'Ganho de Energia': '2.80e-07' },
          { 'Rank': 28, 'Ganho de Energia': '5.61e-07' },
          { 'Rank': 29, 'Ganho de Energia': '1.12e-06' },
          { 'Rank': 30, 'Ganho de Energia': '2.24e-06' },
          { 'Rank': 31, 'Ganho de Energia': '4.49e-06' },
          { 'Rank': 32, 'Ganho de Energia': '8.98e-06' },
          { 'Rank': 33, 'Ganho de Energia': '0.0000179' },
          { 'Rank': 34, 'Ganho de Energia': '0.0000359' },
          { 'Rank': 35, 'Ganho de Energia': '0.0000718' },
          { 'Rank': 36, 'Ganho de Energia': '0.000143' },
          { 'Rank': 37, 'Ganho de Energia': '0.000287' },
          { 'Rank': 38, 'Ganho de Energia': '0.000574' },
          { 'Rank': 39, 'Ganho de Energia': '0.00114' },
          { 'Rank': 40, 'Ganho de Energia': '0.00229' },
          { 'Rank': 41, 'Ganho de Energia': '0.00459' },
          { 'Rank': 42, 'Ganho de Energia': '0.00919' },
          { 'Rank': 43, 'Ganho de Energia': '0.0183' },
          { 'Rank': 44, 'Ganho de Energia': '0.0367' },
          { 'Rank': 45, 'Ganho de Energia': '0.0735' },
          { 'Rank': 46, 'Ganho de Energia': '0.147' },
          { 'Rank': 47, 'Ganho de Energia': '0.294' },
          { 'Rank': 48, 'Ganho de Energia': '0.588' },
          { 'Rank': 49, 'Ganho de Energia': '1.17' },
          { 'Rank': 50, 'Ganho de Energia': '2.35' },
          { 'Rank': 51, 'Ganho de Energia': '4.71' },
          { 'Rank': 52, 'Ganho de Energia': '9.42' },
          { 'Rank': 53, 'Ganho de Energia': '18.8' },
          { 'Rank': 54, 'Ganho de Energia': '37.7' },
          { 'Rank': 55, 'Ganho de Energia': '75.4' },
          { 'Rank': 56, 'Ganho de Energia': '150' },
          { 'Rank': 57, 'Ganho de Energia': '301' },
          { 'Rank': 58, 'Ganho de Energia': '603' },
          { 'Rank': 59, 'Ganho de Energia': '1.20k' },
          { 'Rank': 60, 'Ganho de Energia': '2.41k' },
          { 'Rank': 61, 'Ganho de Energia': '4.83k' },
          { 'Rank': 62, 'Ganho de Energia': '9.66k' },
          { 'Rank': 63, 'Ganho de Energia': '19.3k' },
          { 'Rank': 64, 'Ganho de Energia': '38.6k' },
          { 'Rank': 65, 'Ganho de Energia': '77.2k' },
          { 'Rank': 66, 'Ganho de Energia': '154k' },
          { 'Rank': 67, 'Ganho de Energia': '308k' },
          { 'Rank': 68, 'Ganho de Energia': '617k' },
          { 'Rank': 69, 'Ganho de Energia': '1.23M' },
          { 'Rank': 70, 'Ganho de Energia': '2.47M' },
          { 'Rank': 71, 'Ganho de Energia': '4.94M' },
          { 'Rank': 72, 'Ganho de Energia': '9.88M' },
          { 'Rank': 73, 'Ganho de Energia': '19.7M' },
          { 'Rank': 74, 'Ganho de Energia': '39.5M' },
          { 'Rank': 75, 'Ganho de Energia': '79.0M' },
          { 'Rank': 76, 'Ganho de Energia': '158M' },
          { 'Rank': 77, 'Ganho de Energia': '316M' },
          { 'Rank': 78, 'Ganho de Energia': '632M' },
          { 'Rank': 79, 'Ganho de Energia': '1.26B' },
          { 'Rank': 80, 'Ganho de Energia': '2.52B' },
          { 'Rank': 81, 'Ganho de Energia': '5.05B' },
          { 'Rank': 82, 'Ganho de Energia': '10.1B' },
          { 'Rank': 83, 'Ganho de Energia': '20.2B' },
          { 'Rank': 84, 'Ganho de Energia': '40.4B' },
          { 'Rank': 85, 'Ganho de Energia': '80.9T' },
          { 'Rank': 86, 'Ganho de Energia': '161T' },
          { 'Rank': 87, 'Ganho de Energia': '323T' },
          { 'Rank': 88, 'Ganho de Energia': '647T' },
          { 'Rank': 89, 'Ganho de Energia': '1.29qd' },
          { 'Rank': 90, 'Ganho de Energia': '2.58qd' },
          { 'Rank': 91, 'Ganho de Energia': '5.17qd' },
          { 'Rank': 92, 'Ganho de Energia': '10.3qd' },
          { 'Rank': 93, 'Ganho de Energia': '20.7qd' },
          { 'Rank': 94, 'Ganho de Energia': '41.4qd' },
          { 'Rank': 95, 'Ganho de Energia': '82.8Qn' },
          { 'Rank': 96, 'Ganho de Energia': '165Qn' },
          { 'Rank': 97, 'Ganho de Energia': '331Qn' },
          { 'Rank': 98, 'Ganho de Energia': '663Qn' },
          { 'Rank': 99, 'Ganho de Energia': '1.32sx' },
          { 'Rank': 100, 'Ganho de Energia': '2.65sx' },
          { 'Rank': 101, 'Ganho de Energia': '5.31sx' },
          { 'Rank': 102, 'Ganho de Energia': '10.6sx' },
          { 'Rank': 103, 'Ganho de Energia': '21.2sx' },
          { 'Rank': 104, 'Ganho de Energia': '42.5Sp' },
          { 'Rank': 105, 'Ganho de Energia': '85.1Sp' },
          { 'Rank': 106, 'Ganho de Energia': '170Sp' },
          { 'Rank': 107, 'Ganho de Energia': '340Sp' },
          { 'Rank': 108, 'Ganho de Energia': '681Sp' },
          { 'Rank': 109, 'Ganho de Energia': '1.36O' },
          { 'Rank': 110, 'Ganho de Energia': '2.72O' },
        ]
      }
    }
};
