import type { WikiArticle } from '@/lib/types';

export const upgradesCostsArticle: Omit<WikiArticle, 'createdAt'> = {
  id: 'upgrades-costs',
  title: 'Custos de Upgrades',
  summary: 'Uma referência completa dos custos para cada nível de upgrade para Velocidade de Estrela, Sorte, Chance Crítica de Energia, EXP e outros bônus gerais.',
  content: `Esta página detalha os custos em moedas para cada nível de upgrade em várias categorias de bônus permanentes no jogo, além dos custos em Exchange Tokens para expandir os slots do inventário.

**Novos Códigos:**
Use os códigos \`Update20\`, \`320KLikes\`, \`325KLikes\`, \`590KFav\`, \`595KFav\`, \`Update19P3\`, \`315KLikes\`, \`580KFav\`, \`585KFav\`, e \`150MVisits\`, \`Update19P2Shutdown2\`, \`RandomUpdate19P2Code\`, \`Update19P2Shutdown\`, \`Update19P2\`, \`310KLikes\`, \`570KFav\`, \`575KFav\`, \`125MVisits\`, \`Update19P2Delay\`, \`Update19\`, \`300KLikes\`, \`305KLikes\`, \`560KFav\`, \`565KFav\`, \`Update19Delay\`, \`JustACodeFor19Upd\`, \`Update18P3Keys\`, \`Update18P3\`, \`290KLikes\`, \`295KLikes\`, \`550KFav\`, \`555KFav\` para recompensas!
  `,
  tags: ['custos', 'upgrade', 'evolução', 'preços', 'sorte', 'exp', 'dano', 'energia', 'moedas', 'guia', 'inventário', 'token', 'códigos'],
  imageUrl: 'wiki-13', // Reusing scientific notation image as it relates to costs
  tables: {
    starSpeed: {
      headers: ['Upgrade', 'Custo'],
      rows: [
        { Upgrade: 1, Custo: '15M' },
        { Upgrade: 2, Custo: '450M' },
        { Upgrade: 3, Custo: '5B' },
        { Upgrade: 4, Custo: '10B' },
        { Upgrade: 5, Custo: '500B' },
        { Upgrade: 6, Custo: '500B' },
        { Upgrade: 7, Custo: '1T' },
        { Upgrade: 8, Custo: '5T' },
        { Upgrade: 9, Custo: '10T' },
        { Upgrade: 10, Custo: '50T' },
        { Upgrade: 11, Custo: '5qd' },
        { Upgrade: 12, Custo: '1Qn' },
      ],
    },
    starLuck: {
      headers: ['Upgrade', 'Custo'],
      rows: [
        { Upgrade: 1, Custo: '1M' },
        { Upgrade: 2, Custo: '5M' },
        { Upgrade: 3, Custo: '15M' },
        { Upgrade: 4, Custo: '50M' },
        { Upgrade: 5, Custo: '100M' },
        { Upgrade: 6, Custo: '450M' },
        { Upgrade: 7, Custo: '1B' },
        { Upgrade: 8, Custo: '5B' },
        { Upgrade: 9, Custo: '10B' },
        { Upgrade: 10, Custo: '35B' },
        { Upgrade: 11, Custo: '500B' },
        { Upgrade: 12, Custo: '10T' },
        { Upgrade: 13, Custo: '50T' },
        { Upgrade: 14, Custo: '200T' },
        { Upgrade: 15, Custo: '900T' },
        { Upgrade: 16, Custo: '5qd' },
        { Upgrade: 17, Custo: '80qd' },
        { Upgrade: 18, Custo: '600qd' },
        { Upgrade: 19, Custo: '7Qn' },
        { Upgrade: 20, Custo: '250Qn' },
        { Upgrade: 21, Custo: '50Sp' },
        { Upgrade: 22, Custo: '2O' },
        { Upgrade: 23, Custo: '1N' },
        { Upgrade: 24, Custo: '150N' },
        { Upgrade: 25, Custo: '20de' },
      ],
    },
    criticalEnergy: {
      headers: ['Upgrade', 'Custo'],
      rows: [
        { Upgrade: 1, Custo: '10B' },
        { Upgrade: 2, Custo: '100B' },
        { Upgrade: 3, Custo: '1T' },
        { Upgrade: 4, Custo: '10T' },
        { Upgrade: 5, Custo: '100T' },
        { Upgrade: 6, Custo: '1qd' },
        { Upgrade: 7, Custo: '10qd' },
        { Upgrade: 8, Custo: '100qd' },
        { Upgrade: 9, Custo: '1Qn' },
        { Upgrade: 10, Custo: '10Qn' },
        { Upgrade: 11, Custo: '100Qn' },
        { Upgrade: 12, Custo: '10sx' },
        { Upgrade: 13, Custo: '1Sp' },
        { Upgrade: 14, Custo: '50Sp' },
        { Upgrade: 15, Custo: '500Sp' },
      ],
    },
    exp: {
      headers: ['Upgrade', 'Custo'],
      rows: [
        { Upgrade: 1, Custo: '1M' },
        { Upgrade: 2, Custo: '50M' },
        { Upgrade: 3, Custo: '450M' },
        { Upgrade: 4, Custo: '1B' },
        { Upgrade: 5, Custo: '10B' },
        { Upgrade: 6, Custo: '100B' },
        { Upgrade: 7, Custo: '5T' },
        { Upgrade: 8, Custo: '40T' },
        { Upgrade: 9, Custo: '700T' },
        { Upgrade: 10, Custo: '5qd' },
        { Upgrade: 11, Custo: '9qd' },
        { Upgrade: 12, Custo: '20qd' },
        { Upgrade: 13, Custo: '60qd' },
        { Upgrade: 14, Custo: '100qd' },
        { Upgrade: 15, Custo: '400qd' },
      ],
    },
    generalBonuses: {
        headers: ['Upgrade', 'Custo'],
        rows: [
            { Upgrade: 1, Custo: '1M' },
            { Upgrade: 2, Custo: '5M' },
            { Upgrade: 3, Custo: '15M' },
            { Upgrade: 4, Custo: '50M' },
            { Upgrade: 5, Custo: '100M' },
            { Upgrade: 6, Custo: '450M' },
            { Upgrade: 7, Custo: '1B' },
            { Upgrade: 8, Custo: '5B' },
            { Upgrade: 9, Custo: '10B' },
            { Upgrade: 10, Custo: '35B' },
            { Upgrade: 11, Custo: '100B' },
            { Upgrade: 12, Custo: '500B' },
            { Upgrade: 13, Custo: '1T' },
            { Upgrade: 14, Custo: '5T' },
            { Upgrade: 15, Custo: '10T' },
            { Upgrade: 16, Custo: '50T' },
            { Upgrade: 17, Custo: '200T' },
            { Upgrade: 18, Custo: '900T' },
            { Upgrade: 19, Custo: '5qd' },
            { Upgrade: 20, Custo: '80qd' },
            { Upgrade: 21, Custo: '200qd' },
            { Upgrade: 22, Custo: '600qd' },
            { Upgrade: 23, Custo: '1Qn' },
            { Upgrade: 24, Custo: '7Qn' },
            { Upgrade: 25, Custo: '25Qn' },
            { Upgrade: 26, Custo: '250Qn' },
            { Upgrade: 27, Custo: '900Qn' },
            { Upgrade: 28, Custo: '3.3sx' },
            { Upgrade: 29, Custo: '60sx' },
            { Upgrade: 30, Custo: '100sx' },
            { Upgrade: 31, Custo: '5Sp' },
            { Upgrade: 32, Custo: '70Sp' },
            { Upgrade: 33, Custo: '1O' },
            { Upgrade: 34, Custo: '50O' },
            { Upgrade: 35, Custo: '500O' },
            { Upgrade: 36, Custo: '5N' },
            { Upgrade: 37, Custo: '20N' },
            { Upgrade: 38, Custo: '100N' },
            { Upgrade: 39, Custo: '1.5de' },
            { Upgrade: 40, Custo: '20de' },
            { Upgrade: 41, Custo: '150de' },
            { Upgrade: 42, Custo: '1Ud' },
            { Upgrade: 43, Custo: '15Ud' },
            { Upgrade: 44, Custo: '500Ud' },
            { Upgrade: 45, Custo: '5DD' },
        ]
    },
    attackRange1: {
      headers: ['Attack Range', 'Costs'],
      rows: [
        { 'Attack Range': 1, Costs: 50 },
        { 'Attack Range': 2, Costs: 75 },
        { 'Attack Range': 3, Costs: 100 },
        { 'Attack Range': 4, Costs: 125 },
        { 'Attack Range': 5, Costs: 150 },
        { 'Attack Range': 6, Costs: 175 },
        { 'Attack Range': 7, Costs: 200 },
        { 'Attack Range': 8, Costs: 250 },
        { 'Attack Range': 9, Costs: 300 },
        { 'Attack Range': 10, Costs: 350 },
      ]
    },
    attackRange2: {
      headers: ['Attack Range 2', 'Costs'],
      rows: [
        { 'Attack Range 2': 1, Costs: 500 },
        { 'Attack Range 2': 2, Costs: 750 },
        { 'Attack Range 2': 3, Costs: 1250 },
        { 'Attack Range 2': 4, Costs: 2500 },
      ]
    },
    inventorySlots: {
      headers: ['Upgrade', 'Champions', 'Accessories', 'Weapons', 'Titans', 'Stands', 'Jewelry'],
      rows: [
        { Upgrade: '1', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
        { Upgrade: '2', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
        { Upgrade: '3', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
        { Upgrade: '4', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
        { Upgrade: '5', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
        { Upgrade: '6', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
        { Upgrade: '7', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
        { Upgrade: '8', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
        { Upgrade: '9', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
        { Upgrade: '10', Champions: '1k', Accessories: '1k', Weapons: '1k', Titans: '1k', Stands: '1k', Jewelry: '1k' },
      ]
    }
  },
};
